
= scan a host
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 11-02-2024


== links

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/security_hardening/index

[source,shell]
----
[root@test.build.example.com ~]# source ~/lab-build-proxy.sh 
[root@test.build.example.com ~]# dnf install wget bzip2 openscap-scanner
curl -O https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.oval.xml.bz2
bzip2 --decompress  rhel-8.oval.xml.bz2
...
----

[source,shell]
....
[root@test.build.example.com ~]# oscap oval eval --report vulnerability.html rhel-8.oval.xml
Definition oval:com.redhat.rhsa:def:20240752: false
Definition oval:com.redhat.rhsa:def:20240748: false
Definition oval:com.redhat.rhsa:def:20240647: false
...thousands of these...
Definition oval:com.redhat.rhba:def:20193384: false
Definition oval:com.redhat.rhba:def:20192715: false
Definition oval:com.redhat.rhba:def:20191992: false
Evaluation done.
[root@test.build.example.com ~]# 
....


== SCAP Security Guide (SSG)

Loading the Default SCAP Contents

[source,shell]
----
[root@satellite.build.example.com ~]# ls /usr/share/xml/scap/ssg/content/
ssg-firefox-cpe-dictionary.xml  ssg-rhel6-ds.xml              ssg-rhel7-xccdf.xml
ssg-firefox-cpe-oval.xml        ssg-rhel6-ocil.xml            ssg-rhel8-cpe-dictionary.xml
ssg-firefox-ds-1.2.xml          ssg-rhel6-oval.xml            ssg-rhel8-cpe-oval.xml
ssg-firefox-ds.xml              ssg-rhel6-xccdf.xml           ssg-rhel8-ds-1.2.xml
ssg-firefox-ocil.xml            ssg-rhel7-cpe-dictionary.xml  ssg-rhel8-ds.xml
ssg-firefox-oval.xml            ssg-rhel7-cpe-oval.xml        ssg-rhel8-ocil.xml
ssg-firefox-xccdf.xml           ssg-rhel7-ds-1.2.xml          ssg-rhel8-oval.xml
ssg-rhel6-cpe-dictionary.xml    ssg-rhel7-ds.xml              ssg-rhel8-xccdf.xml
ssg-rhel6-cpe-oval.xml          ssg-rhel7-ocil.xml
ssg-rhel6-ds-1.2.xml            ssg-rhel7-oval.xml
[root@satellite.build.example.com ~]# 
----

[source,shell]
----
[root@satellite.build.example.com ~]# oscap info /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml
Document type: Source Data Stream
Imported: 2023-08-21T08:19:39

Stream: scap_org.open-scap_datastream_from_xccdf_ssg-rhel8-xccdf.xml
Generated: (null)
Version: 1.3
Checklists:
	Ref-Id: scap_org.open-scap_cref_ssg-rhel8-xccdf.xml
WARNING: Datastream component 'scap_org.open-scap_cref_security-data-oval-v2-RHEL8-rhel-8.oval.xml.bz2' points out to the remote 'https://access.redhat.com/security/data/oval/v2/RHEL8/rhel-8.oval.xml.bz2'. Use '--fetch-remote-resources' option to download it.
WARNING: Skipping 'https://access.redhat.com/security/data/oval/v2/RHEL8/rhel-8.oval.xml.bz2' file which is referenced from datastream
		Status: draft
		Generated: 2023-08-21
		Resolved: true
		Profiles:
			Title: ANSSI-BP-028 (enhanced)
				Id: xccdf_org.ssgproject.content_profile_anssi_bp28_enhanced
			Title: ANSSI-BP-028 (high)
				Id: xccdf_org.ssgproject.content_profile_anssi_bp28_high
			Title: ANSSI-BP-028 (intermediary)
				Id: xccdf_org.ssgproject.content_profile_anssi_bp28_intermediary
			Title: ANSSI-BP-028 (minimal)
				Id: xccdf_org.ssgproject.content_profile_anssi_bp28_minimal
			Title: CIS Red Hat Enterprise Linux 8 Benchmark for Level 2 - Server
				Id: xccdf_org.ssgproject.content_profile_cis
			Title: CIS Red Hat Enterprise Linux 8 Benchmark for Level 1 - Server
				Id: xccdf_org.ssgproject.content_profile_cis_server_l1
			Title: CIS Red Hat Enterprise Linux 8 Benchmark for Level 1 - Workstation
				Id: xccdf_org.ssgproject.content_profile_cis_workstation_l1
			Title: CIS Red Hat Enterprise Linux 8 Benchmark for Level 2 - Workstation
				Id: xccdf_org.ssgproject.content_profile_cis_workstation_l2
			Title: Unclassified Information in Non-federal Information Systems and Organizations (NIST 800-171)
				Id: xccdf_org.ssgproject.content_profile_cui
			Title: Australian Cyber Security Centre (ACSC) Essential Eight
				Id: xccdf_org.ssgproject.content_profile_e8
			Title: Health Insurance Portability and Accountability Act (HIPAA)
				Id: xccdf_org.ssgproject.content_profile_hipaa
			Title: Australian Cyber Security Centre (ACSC) ISM Official
				Id: xccdf_org.ssgproject.content_profile_ism_o
			Title: Protection Profile for General Purpose Operating Systems
				Id: xccdf_org.ssgproject.content_profile_ospp
			Title: PCI-DSS v3.2.1 Control Baseline for Red Hat Enterprise Linux 8
				Id: xccdf_org.ssgproject.content_profile_pci-dss
			Title: DISA STIG for Red Hat Enterprise Linux 8
				Id: xccdf_org.ssgproject.content_profile_stig
			Title: DISA STIG with GUI for Red Hat Enterprise Linux 8
				Id: xccdf_org.ssgproject.content_profile_stig_gui
		Referenced check files:
			ssg-rhel8-oval.xml
				system: http://oval.mitre.org/XMLSchema/oval-definitions-5
			ssg-rhel8-ocil.xml
				system: http://scap.nist.gov/schema/ocil/2
			security-data-oval-v2-RHEL8-rhel-8.oval.xml.bz2
				system: http://oval.mitre.org/XMLSchema/oval-definitions-5
Checks:
	Ref-Id: scap_org.open-scap_cref_ssg-rhel8-oval.xml
	Ref-Id: scap_org.open-scap_cref_ssg-rhel8-ocil.xml
	Ref-Id: scap_org.open-scap_cref_ssg-rhel8-cpe-oval.xml
	Ref-Id: scap_org.open-scap_cref_security-data-oval-v2-RHEL8-rhel-8.oval.xml.bz2
Dictionaries:
	Ref-Id: scap_org.open-scap_cref_ssg-rhel8-cpe-dictionary.xml
[root@satellite.build.example.com ~]# 
----

[source,shell]
----
[root@satellite.build.example.com ~]# hammer scap-content bulk-upload --type default
Errors:                 
  
Uploaded Scap Contents:

Scap Contents uploaded.
[root@satellite.build.example.com ~]# 
----


== download RHEL 9 SSG package

https://access.redhat.com/documentation/en-us/red_hat_satellite/6.11/html/administering_red_hat_satellite/managing_security_compliance_admin#getting-supported-scap-contents-for-rhel_admin

https://access.redhat.com/downloads/content/scap-security-guide/0.1.69-3.el9_3/noarch/fd431d51/package


== associate things 


associate role theforeman.foreman_scap_client with rhel 8 host gene-debose.build.example.com
js

associate policy 

hosts > host checkbox > select action > Assign Compliance Policy


== run ansible role from Satellite

https://access.redhat.com/solutions/7033411
Executing Ansible Role to apply OpenSCAP compliance policy on client registered with Red Hat Satellite fails with exception : "No package rubygem-foreman_scap_client available."

installs the foreman_scap_client package from repo 
satellite-client-6-for-rhel-8-x86_64-rpms
so this must be enabled.
Either in the Activation key settings, override to enabled 
or 
dnf config-manager --enable satellite-client-6-for-rhel-8-x86_64-rpms

creates 
/etc/cron.d/foreman_scap_client_cron
/etc/foreman_scap_client/config.yaml

[source,shell]
----js
[root@gene-debose.build.example.com ~]$ cat /etc/foreman_scap_client/config.yaml
...
# policy (key is id as in Foreman)
2:
  :profile: 
  :content_path: /var/lib/openscap/content/b7772a4001f865517e30762c406dee80fdab2100ecc010f4408519a979665f6e.xml
  # Download path
  # A path to download SCAP content from proxy
  :download_path: /compliance/policies/2/content/b7772a4001f865517e30762c406dee80fdab2100ecc010f4408519a979665f6e
  :tailoring_path: 
  :tailoring_download_path: 

# OVAL policies
:oval:
[root@gene-debose.build.example.com ~]$ 
----


== run locally


[source,shell]
----
[root@gene-debose.build.example.com ~]$ foreman_scap_client 2
File /var/lib/openscap/content/b7772a4001f865517e30762c406dee80fdab2100ecc010f4408519a979665f6e.xml is missing. Downloading it from proxy.
Download SCAP content xml from: https://satellite.build.example.com:9090/compliance/policies/2/content/b7772a4001f865517e30762c406dee80fdab2100ecc010f4408519a979665f6e
DEBUG: running: oscap xccdf eval  --local-files /root   --results-arf /tmp/d20240211-17057-of6jpp/results.xml /var/lib/openscap/content/b7772a4001f865517e30762c406dee80fdab2100ecc010f4408519a979665f6e.xml
WARNING: Data stream component 'scap_org.open-scap_cref_security-data-oval-v2-RHEL8-rhel-8.oval.xml.bz2' points out to the remote 'https://access.redhat.com/security/data/oval/v2/RHEL8/rhel-8.oval.xml.bz2'. The option --local-files '/root' has been provided, but the file '/root/security-data-oval-v2-RHEL8-rhel-8.oval.xml.bz2' can't be used locally: No such file or directory.
WARNING: Skipping ./security-data-oval-v2-RHEL8-rhel-8.oval.xml.bz2 file which is referenced from XCCDF content
DEBUG: running: /usr/bin/env bzip2 /tmp/d20240211-17057-of6jpp/results.xml
Uploading results to https://satellite.build.example.com:9090/compliance/arf/2
Report uploaded, report id: 9
[root@gene-debose.build.example.com ~]$ 
----

Tried 

[source,shell]
----
source ./lab-proxy.sh 
curl -O https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.oval.xml.bz2
ln -s rhel-8.oval.xml.bz2 /root/security-data-oval-v2-RHEL8-rhel-8.oval.xml.bz2
----

no difference

tried 
satellite
cd /usr/share/xml/scap/ssg/content/
scp ssg-rhel8-ds.xml 192.168.13.153:

gene-debose

manual run with oscap

[source,shell]
----
oscap xccdf eval \
  --profile xccdf_org.ssgproject.content_profile_stig \
  --rule xccdf_org.ssgproject.content_rule_security_patches_up_to_date \
  --fetch-remote-resources  \
  /root/ssg-rhel8-ds.xml
----


[source,shell]
----
[root@gene-debose.build.example.com ~]$ oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_stig --rule xccdf_org.ssgproject.content_rule_security_patches_up_to_date --fetch-remote-resources  /root/ssg-rhel8-ds.xml
Downloading: https://access.redhat.com/security/data/oval/v2/RHEL8/rhel-8.oval.xml.bz2 ... ok
--- Starting Evaluation ---

Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
Ident   CCE-80865-9
OVAL Definition ID	oval:com.redhat.rhsa:def:20240752
OVAL Definition Title	RHSA-2024:0752: container-tools:rhel8 security update (Important)
Result  pass

...loads of these ...

Title   Ensure Software Patches Installed
Rule    xccdf_org.ssgproject.content_rule_security_patches_up_to_date
Ident   CCE-80865-9
OVAL Definition ID	oval:com.redhat.rhba:def:20191992
OVAL Definition Title	RHBA-2019:1992: cloud-init bug fix and enhancement update (Moderate)
Result  pass

[root@gene-debose.build.example.com ~]$ 
----



== view locally generated report 

Hosts > Reports > Full report

a few table, but _No rules were evaluated._

